print("enter three numbers")
first = input("number 1 :")
second = input("number 2 :")
third = input("number 3 :")
print("Your numbers forward:")
print(first)
print(second)
print(third)
print("your numbers reversed:")
print(third)
print(second)
print(first)