number =input("Enter first number")
number2 =input("Enter second number")
number3 =input("Enter third number")
number4 =input("Enter fourth number")
number5 =input("Enter fifth number")
print(number)
print(number2)
print(number3)
print(number4)
print(number5)
